### ISSUE TITLE
KMS "Sign" operation is not suppored

### ISSUE THREAD

**Issue by WaylandAce** [async-aws/aws#1342]
Hello!
It seems, what async-aws lib does not support KMS::Sign operation.

https://docs.aws.amazon.com/kms/latest/APIReference/API_Sign.html

Do you plan to add it in near future?

**Comment by jderusse** [comment]
Hey, async-aws does not provide all operations by default on purpose.
Instead of generating thousands of operations that will never be used (and will increase the size of the package), we wait for someone to have a use case, and need it.

If you want, you can add this operation by following this documentation: https://async-aws.com/contribute/generate.html#creating-a-new-client-operation
