### ISSUE TITLE
Amazon SQS JSON protocol instead of Query protocol

### ISSUE THREAD

**Issue by Ferror** [async-aws/aws#1530]
## Introduction
This issue is a feature request to represent and maybe an open discussion about such a feature possibility. Amazon says that it should be available only by updating the AWS-SDK version, so for us, I guess it's just specifying the latest API Version when sending the request.

## References
* https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-json-faqs.html#json-protocol-getting-started
* https://aws.amazon.com/about-aws/whats-new/2023/07/json-protocol-support-amazon-sqs/
* https://github.com/aws/aws-sdk-php/releases/tag/3.269.6

**Comment by jderusse** [comment]
Actually, the protocol used by async AWS is defined by AWS SDK specs.

So AsyncAws will use JSON as soon as the official SDK will use it.

The first link says that the official php SDK switched to JSON in version 3.269.6 (this is visible here https://github.com/aws/aws-sdk-php/blob/343f7088f246d4667172e69d5f2bf440496bb708/src/data/sqs/2012-11-05/api-2.json#L9)

But they forgot to says that it has been reverted in the following version (see commit https://github.com/aws/aws-sdk-php/commit/6262f18d360f223f1853ebe64eb6758ce8fde55d)

I'm not surprised they reverted it, because this is a huge BC break: the JSON protocol is not supported by SQS alternative (or localStack or FakeSqs) which break e2e tests that don't use the real AWS endpoint for dev or tests

**Comment by GrahamCampbell** [comment]
Yeh, their docs are misleading. You need to **downgrade** to the specific version they list, rather than upgrade. ;)

**Comment by stof** [comment]
Yeah, the misleading things in their doc is that "required SDK version" is not a minimum version. It is an exact version.

**Comment by Ferror** [comment]
New thing just dropped by: https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-sqs-support-json-protocol/

**Comment by stof** [comment]
@Ferror see #1601 where the code switches to the JSON protocol by reflecting the change done in the official PHP SDK. This will come soon in async-aws (we first need to make our CI green for it)

**Comment by Ferror** [comment]
Let me also relate this issue to the localstack support PR: https://github.com/localstack/localstack/pull/8268

**Comment by GrahamCampbell** [comment]
This is now available on our sqs package via `^2.0@dev`. Though note that you may experience an issue (that I am still looking in to): https://github.com/async-aws/aws/issues/1620.

**Comment by stof** [comment]
I'm closing this issue as `async-aws/sqs` 2.0 has already been released.
