### ISSUE TITLE
How to use async-aws DynamoDB query & scan with pagination?

### ISSUE THREAD

**Issue by hassaan-dev** [async-aws/aws#1562]
Hi,

I must say, this is very cool and awesome library and 100% recommended to use instead of `AWS-SDK`. As this more efficient and very light weight.

I am using DynamoDB for one of my application. The main purpose is to store logs into DynamoDB. I am storing them using `async-aws` But I am in problem for fetching records.

Let's suppose I have following Database schema

id                 _`string | Partition Key`_
user_id       _`string`_
log_id _`sting`_
log_type _`string`_
created_at _`string | timestamp`_

**User ID**, **Log ID**, **Log Type** can have multiple entries.

I am trying to fetch records against `User ID` this surely have multiple entries. The documentation [Get an Item](https://async-aws.com/clients/dynamodb.html#get-an-item) will not used in this case. 

I need to use `FilterExpression`, `ExpressionAttributeValues` & `Limit` etc to get records against `User ID` with paging but I am surprised that I am unable to find any example or documentation regarding this.

Is this supported in [async-aws/dynamo-db](https://github.com/async-aws/dynamo-db), If yes, can some please help me with this?

**Comment by GrahamCampbell** [comment]
DynamoDB does not support this access pattern (efficiently) of arbitrary filtering by attributes. One should either use secondary indexes or use a carefuly chosen partition and sort key, to enable the specific query patterns you need. With dynamodb, you need to think first about the access patterns you need, rather than how to normalize the data (indeed, you may not even want to always normalize all the way).

**Comment by GrahamCampbell** [comment]
I'd highly recommend Alex Debrie's book and talks on DynamoDB, to help you get started.

https://www.dynamodbbook.com/

**Comment by hassaan-dev** [comment]
> DynamoDB does not support this access pattern (efficiently) of arbitrary filtering by attributes. One should either use secondary indexes or use a carefuly chosen partition and sort key, to enable the specific query patterns you need. With dynamodb, you need to think first about the access patterns you need, rather than how to normalize the data (indeed, you may not even want to always normalize all the way).

1. Using `scan` is efficient than `query`?
2. How to combine pagination with `scan`?
3. Using secondary index is not problem. But question is, what I have to chosen carefully and is anything need to change on code side as well?

**Comment by GrahamCampbell** [comment]
Scan is not something you would normally use in production workloads - it's usual use case is performing a data migration or debugging. If you are finding you cannot fit your workload into dynamodb patterns, dynamodb may be the wrong db for you. The only exception here would be if you have an exceptionally small amount of data in your db, say sub 10k rows, of 4kb each.

**Comment by GrahamCampbell** [comment]
Query support pagination, using a cursor. Offset pagination is not efficient in any database, and particularly not in dynamodb.

**Comment by hassaan-dev** [comment]
> Scan is not something you would normally use in production workloads - it's usual use case is performing a data migration or debugging. If you are finding you cannot fit your workload into dynamodb patterns, dynamodb may be the wrong db for you. The only exception here would be if you have an exceptionally small amount of data in your db, say sub 10k rows, of 4kb each.

1. Can I use `query` without `id` mean partition key?
2. If no for above point, then can I `user_id` as secondary partition key and then query from that key? 
3. Is there any documentation or example for pagination?

**Comment by GrahamCampbell** [comment]
Correct, query is only really useful when you have a sort key, otherwise you are just matching zero or one item. Yes, in the dynamodb docs, you can see that there's an "exclusive start key" in requests and responses that you can use as a cursor.

TBH, issue trackers aren't really meant for this kind of discussion - application specific questions not about the library (just using the lubrary). It would be best to move this to a forum or Slack. If you'd like further assistance from my side, please [hit me up](mailto:hello@gjcampbell.co.uk) to discuss rates, or that DynamoDB book by Alex also has all the answers to what you've asked so far. ;)

**Comment by hassaan-dev** [comment]
Thank you @GrahamCampbell for helping me. I appreciate your recommendations. 
I will surely contact you to discuss if there is anything in future. I am closing this issue.
