### ISSUE TITLE
Using env var from DotEnv symfony component

### ISSUE THREAD

**Issue by tyx** [async-aws/aws#632]
Hi !

Currently, using env var `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` loaded from `.env` with DotEnv component seems not working.

I have false result in this getenv call : https://github.com/async-aws/aws/blob/master/src/Core/src/Configuration.php#L96

But I had the correct result in `$_ENV` or `$_SERVER` at the same line.

**Comment by shouze** [comment]
Yes this is a big classic. DotEnv component don't use getenv nor setenv because those methodes are not thread safe.

**Comment by tyx** [comment]
I'm ready to make a PR if needed !

**Comment by nicolas-grekas** [comment]
Please send a PR, no code should use getenv ever :)

**Comment by tyx** [comment]
Could I just replace `getenv` by `$_SERVER` ?

**Comment by nicolas-grekas** [comment]
Looks like you could yes.

**Comment by jderusse** [comment]
@nicolas-grekas do you have some pointers about `getenv` vs `$_SERVER` vs `$_ENV`? why `getenv` is discouraged? why using `$_SERVER` over `$_ENV`?

**Comment by nicolas-grekas** [comment]
getenv/putenv are not thread safe. In practice, this means that if a script calls putenv, an concurrent request can have getenv return null.
This happens trivially on Windows where thread safety is important.

**Comment by shouze** [comment]
@jderusse putenv/getenv are [not thread safe](https://github.com/symfony/symfony/blob/87c9ab4cbe89e90236a453718575e2b93fe5f88b/src/Symfony/Component/Dotenv/Dotenv.php#L194). see also [this one](https://www.php.net/manual/fr/function.getenv.php#119680).

About using `$_SERVER` over `$_ENV` is probably [because of variables order](https://www.php.net/manual/en/ini.core.php#ini.variables-order) no?
![image](https://user-images.githubusercontent.com/54712/82316566-47ca3100-99cd-11ea-8b82-ef9b92c3dba5.png)

**Comment by nicolas-grekas** [comment]
`$_ENV` is not populated by default on e.g Ubuntu. This makes `$_SERVER` the most reliable source for reading env values. Note that ppl should then be sure to never read an env that starts with `HTTP_` since these can be trivially confused with an HTTP header (see https://httpoxy.org/).

**Comment by shouze** [comment]
I've made a PR, let me know if it's ok like that guys :wink:
