### ISSUE TITLE
Decouple from symfony/http-client

### ISSUE THREAD

**Issue by ostrolucky** [async-aws/aws#756]
I don't want to be forced to instal symfony/http-client. Can't this package be decoupled from it and use only contracts, or extracted to package which is decoupled?

**Comment by jderusse** [comment]
I agree with decoupling, we only need a `symfony/http-client-contracts` or a `symfony/http-client-implementation`. 

But I personally don't like libraries that only require a contract (or a "provider" virtual package) and ask you to add an implementation.
It's frustrating and source of confusion for end users.

I would like beeing able to tell composer "I want a package that provide this implementation, if none are installed, use this one". But it's not possible at the moment https://github.com/composer/composer/issues/6758 that's why I'm :-1: for this.

**Comment by ostrolucky** [comment]
Then you can go with second approach I suggested. Have a tiny wrapper package that comes with `symfony/http-client` and requires `async-aws/core` which requires contracts only.

**Comment by jderusse** [comment]
given `async-aws` provides 1 package per service and they all required `async-aws/core`, we'll have to do the same for the current 25 packages.
That too much work for maintaining.

Out of curiosity, what alternative implements the `symfony/http-client-contracts`?

**Comment by ostrolucky** [comment]
I don't know what alternative implements it, I just wanted to write adapter for some PSR client and use that.

**Comment by Nyholm** [comment]
I've played with the idea a few times. But I find that 

1) It is really difficult to implement the `symfony/http-client-contracts`. 
2) It makes things unnecessary complicated for the user if we dont require symfony/http-client

For example, how do we create a new HttpClient object if none is passed to us? Either we say "You need to install symfony/http-client", but since that is the only public implementation, why not require it and use it? 

With that said, There is nothing stopping you from passing your custom HttpClientInterface to use with AsyncAws, the downside is that you need to install `symfony/http-client` without using it. 

Or is there something blocking you from using a custom HTTP client?

**Comment by ostrolucky** [comment]
Honestly, I don't know. I just never liked that official aws libraries require guzzle, but on the other hand your packages require Symfony httpclient, so that's not different. I thought ecosystem is past doing this kind of thing for new packages. So no, this is not the problem right now, but history taught us this will become a problem. Symfony http client will break the BC at some point. At this point, users will be blocked from installing this package if they still use libraries requiring older http client API.

**Comment by ostrolucky** [comment]
Let's close for now then, it will make more sense to open this with more available implementations
